<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use RuntimeException;

/**
 * Cross-references the deterministic roster markdown file
 * (`Subject And Prerequisuite/Students-Profile.md`, generated by
 * `students:generate-roster-file`) against `student_profiles.enrollment_category`
 * in the database, and writes a companion file listing only the students the
 * real `ClassifyEnrollmentStanding` derived as Irregular.
 *
 * The roster file's own `Category` column is always `Regular` by design (see
 * `GenerateStudentRosterFile` — it is a pure, DB-free generator). Real
 * Regular/Irregular standing only exists once `StudentRosterSeeder` has
 * built real grade history and derived it, so this command requires that
 * seeder to have already run.
 */
final class GenerateIrregularStudentReport extends Command
{
    protected $signature = 'students:generate-irregular-report
        {--path= : Override the output file path (defaults to Subject And Prerequisuite/Irregular-Students.md at the project root)}
        {--roster-path= : Override the source roster file path (defaults to Subject And Prerequisuite/Students-Profile.md)}';

    protected $description = 'List every roster student the database has derived as Irregular, from real seeded grade history';

    private const DEFAULT_OUTPUT_PATH = __DIR__.'/../../../../Subject And Prerequisuite/Irregular-Students.md';

    private const DEFAULT_ROSTER_PATH = __DIR__.'/../../../../Subject And Prerequisuite/Students-Profile.md';

    private const STUDENT_NUMBER_PATTERN = '/^\d{4}-\d{2}-\d{5}$/';

    public function handle(): int
    {
        $this->guardEnvironment();

        $rosterPath = $this->stringOption('roster-path') ?? self::DEFAULT_ROSTER_PATH;
        $outputPath = $this->stringOption('path') ?? self::DEFAULT_OUTPUT_PATH;

        $rows = $this->parseRoster($rosterPath);
        $categoryByStudentNumber = $this->categoriesFor(array_column($rows, 'student_number'));

        if ($categoryByStudentNumber === []) {
            throw new RuntimeException(
                'No roster student numbers were found in student_profiles. Run StudentRosterSeeder '.
                '(php artisan db:seed --class=StudentRosterSeeder) before generating this report.',
            );
        }

        $irregular = array_values(array_filter(
            $rows,
            static fn (array $row): bool => ($categoryByStudentNumber[$row['student_number']] ?? null) === 'irregular',
        ));

        File::ensureDirectoryExists(dirname($outputPath));
        File::put($outputPath, $this->renderContents($irregular));
        $this->info("Wrote irregular student report to {$outputPath}.");

        return self::SUCCESS;
    }

    private function stringOption(string $name): ?string
    {
        $value = $this->option($name);

        return is_string($value) && $value !== '' ? $value : null;
    }

    /**
     * @param  list<string>  $studentNumbers
     * @return array<string, string>
     */
    private function categoriesFor(array $studentNumbers): array
    {
        if ($studentNumbers === []) {
            return [];
        }

        return DB::table('student_profiles')
            ->whereIn('student_number', $studentNumbers)
            ->whereNotNull('enrollment_category')
            ->pluck('enrollment_category', 'student_number')
            ->all();
    }

    /**
     * @param  list<array{student_number: string, name: string, email: string, program_code: string, section_code: string, year_level: int}>  $rows
     */
    private function renderContents(array $rows): string
    {
        $semesterInfo = $this->loadSemesterInfo(array_column($rows, 'student_number'));
        $termLabel = $semesterInfo['term_label'] ?? 'Current Term';
        $studentSemesterData = $semesterInfo['students'] ?? [];

        $lines = [
            '# Irregular Students',
            '',
            'Generated by `php artisan students:generate-irregular-report` — edit the command, not this file.',
            'Cross-references `Subject And Prerequisuite/Students-Profile.md` against `student_profiles.enrollment_category`',
            'in the local database, derived by the real `ClassifyEnrollmentStanding` from actual seeded grade history',
            '(`Database\\Seeders\\StudentRosterSeeder`). A student appears here only when the database itself derived them',
            'as Irregular — never a guess.',
            '',
            "**Active Academic Term:** {$termLabel}",
            '**Total irregular students:** '.count($rows),
            '',
            '## Seeded Roster Irregular Students',
            '',
            '| Student No. | Name | Email | Program | Section | Year | Sem Status | Units | Enrolled Subjects | Irregular Notes |',
            '|---|---|---|---|---|---|---|---|---|---|',
        ];

        foreach ($rows as $row) {
            $sem = $studentSemesterData[$row['student_number']] ?? [
                'status' => 'Not enrolled this term',
                'units' => '0.0',
                'subjects' => '—',
                'notes' => 'Irregular standing',
            ];

            $lines[] = sprintf(
                '| %s | %s | %s | %s | %s | %d | %s | %s | %s | %s |',
                $row['student_number'],
                $row['name'],
                $row['email'],
                $row['program_code'],
                $row['section_code'],
                $row['year_level'],
                $sem['status'],
                $sem['units'],
                $sem['subjects'],
                $sem['notes'],
            );
        }

        $cohortIrregulars = $this->loadCohortIrregulars($termLabel);
        if ($cohortIrregulars !== []) {
            $lines[] = '';
            $lines[] = "## Active Institutional Test Cohorts ({$termLabel})";
            $lines[] = '';
            $lines[] = '| Student No. | Name | Email | Program | Year | Sem Status | Units | Enrolled Subjects |';
            $lines[] = '|---|---|---|---|---|---|---|---|';
            foreach ($cohortIrregulars as $cohort) {
                $lines[] = sprintf(
                    '| %s | %s | %s | %s | %d | %s | %s | %s |',
                    $cohort['student_number'],
                    $cohort['name'],
                    $cohort['email'],
                    $cohort['program_code'],
                    $cohort['year_level'],
                    $cohort['status'],
                    $cohort['units'],
                    $cohort['subjects'],
                );
            }
        }

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    /**
     * @param  list<string>  $studentNumbers
     * @return array{term_label: string, students: array<string, array{status: string, units: string, subjects: string, notes: string}>}
     */
    private function loadSemesterInfo(array $studentNumbers): array
    {
        if ($studentNumbers === []) {
            return ['term_label' => 'Current Term', 'students' => []];
        }

        $term = DB::table('academic_terms')
            ->where('status', 'semester_ongoing')
            ->first() ?? DB::table('academic_terms')->orderByDesc('id')->first();

        if (! $term) {
            return ['term_label' => 'Current Term', 'students' => []];
        }

        $profiles = DB::table('student_profiles')
            ->whereIn('student_number', $studentNumbers)
            ->get(['id', 'student_number'])
            ->keyBy('student_number');

        $profileIds = $profiles->pluck('id')->all();

        $enrollments = DB::table('enrollments')
            ->where('academic_term_id', $term->id)
            ->whereIn('student_id', $profileIds)
            ->get(['id', 'student_id', 'status', 'total_units'])
            ->keyBy('student_id');

        $enrollmentIds = $enrollments->pluck('id')->all();

        $subjectsByEnrollment = [];
        if ($enrollmentIds !== []) {
            $enrolledSubjects = DB::table('enrollment_subjects')
                ->join('sections', 'sections.id', '=', 'enrollment_subjects.section_id')
                ->join('subjects', 'subjects.id', '=', 'sections.subject_id')
                ->whereIn('enrollment_subjects.enrollment_id', $enrollmentIds)
                ->get(['enrollment_subjects.enrollment_id', 'subjects.code']);

            foreach ($enrolledSubjects as $es) {
                $subjectsByEnrollment[$es->enrollment_id][] = $es->code;
            }
        }

        $failedByStudent = [];
        if ($profileIds !== []) {
            $failedGrades = DB::table('academic_grades')
                ->join('subjects', 'subjects.id', '=', 'academic_grades.subject_id')
                ->whereIn('academic_grades.student_id', $profileIds)
                ->where(function ($q) {
                    $q->whereIn('academic_grades.mark', ['5.00', 'INC', 'DRP', 'NC'])
                      ->orWhere('academic_grades.remarks', 'like', '%fail%');
                })
                ->get(['academic_grades.student_id', 'subjects.code', 'academic_grades.final_grade', 'academic_grades.mark']);

            foreach ($failedGrades as $fg) {
                $failedByStudent[$fg->student_id][] = $fg->code . ' (' . ($fg->final_grade ?? $fg->mark ?? 'Failed') . ')';
            }
        }

        $termLabel = $term->school_year . ' · ' . $term->semester;
        $students = [];

        foreach ($studentNumbers as $no) {
            $profile = $profiles->get($no);
            if (! $profile) {
                continue;
            }

            $enr = $enrollments->get($profile->id);
            $subjs = $enr ? ($subjectsByEnrollment[$enr->id] ?? []) : [];
            $failed = $failedByStudent[$profile->id] ?? [];

            $students[$no] = [
                'status' => $enr ? ucfirst(str_replace('_', ' ', $enr->status)) : 'Not enrolled this term',
                'units' => $enr ? number_format((float) $enr->total_units, 1) : '0.0',
                'subjects' => $subjs !== [] ? implode(', ', array_unique($subjs)) : '—',
                'notes' => $failed !== [] ? 'Backlog: ' . implode(', ', array_unique($failed)) : 'Irregular standing from curriculum evaluation',
            ];
        }

        return [
            'term_label' => $termLabel,
            'students' => $students,
        ];
    }

    /**
     * @return list<array{student_number: string, name: string, email: string, program_code: string, year_level: int, status: string, units: string, subjects: string}>
     */
    private function loadCohortIrregulars(string $termLabel): array
    {
        $term = DB::table('academic_terms')
            ->where('status', 'semester_ongoing')
            ->first() ?? DB::table('academic_terms')->orderByDesc('id')->first();

        if (! $term) {
            return [];
        }

        $cohortProfiles = DB::table('student_profiles')
            ->join('users', 'users.id', '=', 'student_profiles.user_id')
            ->join('programs', 'programs.id', '=', 'student_profiles.program_id')
            ->where('student_profiles.enrollment_category', 'irregular')
            ->where('student_profiles.student_number', 'like', 'TEST-%')
            ->get([
                'student_profiles.student_number',
                'users.name',
                'users.email',
                'programs.code as program_code',
                'student_profiles.year_level',
                'student_profiles.id as profile_id',
            ]);

        if ($cohortProfiles->isEmpty()) {
            return [];
        }

        $profileIds = $cohortProfiles->pluck('profile_id')->all();

        $enrollments = DB::table('enrollments')
            ->where('academic_term_id', $term->id)
            ->whereIn('student_id', $profileIds)
            ->get(['id', 'student_id', 'status', 'total_units'])
            ->keyBy('student_id');

        $enrollmentIds = $enrollments->pluck('id')->all();

        $subjectsByEnrollment = [];
        if ($enrollmentIds !== []) {
            $enrolledSubjects = DB::table('enrollment_subjects')
                ->join('sections', 'sections.id', '=', 'enrollment_subjects.section_id')
                ->join('subjects', 'subjects.id', '=', 'sections.subject_id')
                ->whereIn('enrollment_subjects.enrollment_id', $enrollmentIds)
                ->get(['enrollment_subjects.enrollment_id', 'subjects.code']);

            foreach ($enrolledSubjects as $es) {
                $subjectsByEnrollment[$es->enrollment_id][] = $es->code;
            }
        }

        $rows = [];
        foreach ($cohortProfiles as $cp) {
            $enr = $enrollments->get($cp->profile_id);
            $subjs = $enr ? ($subjectsByEnrollment[$enr->id] ?? []) : [];

            $rows[] = [
                'student_number' => $cp->student_number,
                'name' => $cp->name,
                'email' => $cp->email,
                'program_code' => $cp->program_code,
                'year_level' => (int) $cp->year_level,
                'status' => $enr ? ucfirst(str_replace('_', ' ', $enr->status)) : 'Not enrolled this term',
                'units' => $enr ? number_format((float) $enr->total_units, 1) : '0.0',
                'subjects' => $subjs !== [] ? implode(', ', array_unique($subjs)) : '—',
            ];
        }

        return $rows;
    }

    /**
     * Parses only the `#### SECTION_CODE` roster tables, mirroring
     * `StudentRosterSeeder::parseRoster()` exactly — the `## Summary`
     * block's aggregate tables never carry a `Student No.` column, so a row
     * is only recognized when its first cell matches the `YYYY-NN-NNNNN`
     * student-number shape.
     *
     * @return list<array{student_number: string, name: string, email: string, program_code: string, section_code: string, year_level: int}>
     */
    private function parseRoster(string $path): array
    {
        if (! is_file($path)) {
            throw new RuntimeException("GenerateIrregularStudentReport could not find its roster file at {$path}");
        }

        $rows = [];
        $inSection = false;

        foreach (preg_split('/\R/u', File::get($path)) ?: [] as $line) {
            $trimmed = trim($line);

            if (str_starts_with($trimmed, '#### ')) {
                $inSection = true;

                continue;
            }

            if (str_starts_with($trimmed, '#')) {
                $inSection = false;

                continue;
            }

            if (! $inSection || $trimmed === '' || ! str_starts_with($trimmed, '|')) {
                continue;
            }

            $cells = array_map('trim', explode('|', trim($trimmed, '|')));
            if (count($cells) !== 7 || preg_match(self::STUDENT_NUMBER_PATTERN, $cells[0]) !== 1) {
                continue;
            }

            $rows[] = [
                'student_number' => $cells[0],
                'name' => $cells[1],
                'email' => $cells[2],
                'program_code' => $cells[3],
                'section_code' => $cells[4],
                'year_level' => (int) $cells[5],
            ];
        }

        return $rows;
    }

    private function guardEnvironment(): void
    {
        if (! app()->environment(['local', 'testing'])) {
            throw new RuntimeException('students:generate-irregular-report may only run locally or in testing.');
        }
    }
}
