<?php

namespace App\Console\Commands;

use App\Domain\Identity\StudentIdentityGenerator;
use App\Domain\Organization\CollegeCode;
use App\Domain\Organization\StudentRosterMap;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use RuntimeException;

/**
 * Generates the deterministic local student roster markdown file consumed by
 * downstream demo/seed work (mirrors how `Professor_Department_List.md` feeds
 * `WorkbookFacultyProfileSeeder`). Every value is derived purely from
 * `StudentRosterMap::sections()` and `StudentIdentityGenerator::forIndex()` —
 * no database access, no randomness — so re-running the command reproduces
 * byte-identical output.
 */
final class GenerateStudentRosterFile extends Command
{
    protected $signature = 'students:generate-roster-file
        {--path= : Override the output file path (defaults to Subject And Prerequisuite/Students-Profile.md at the project root)}
        {--check : Compare generated content against the target file without writing; exit 1 on drift}';

    protected $description = 'Generate the deterministic local student roster markdown file from StudentRosterMap and StudentIdentityGenerator';

    private const DEFAULT_PATH = __DIR__.'/../../../../Subject And Prerequisuite/Students-Profile.md';

    /** @var list<CollegeCode> */
    private const COLLEGE_ORDER = [CollegeCode::Coe, CollegeCode::Cbae, CollegeCode::Coa, CollegeCode::Ccs];

    public function handle(): int
    {
        $this->guardEnvironment();

        $path = $this->stringOption('path') ?? self::DEFAULT_PATH;
        $contents = $this->generateContents();

        if ($this->option('check')) {
            return $this->runCheck($path, $contents);
        }

        File::ensureDirectoryExists(dirname($path));
        File::put($path, $contents);
        $this->info("Wrote student roster to {$path}.");

        return self::SUCCESS;
    }

    private function runCheck(string $path, string $contents): int
    {
        $existing = is_file($path) ? File::get($path) : null;

        if ($existing === $contents) {
            $this->info("Students-Profile.md matches generated output ({$path}).");

            return self::SUCCESS;
        }

        if ($existing === null) {
            $this->error("Students-Profile.md does not exist at {$path}.");
        } else {
            $existingLines = substr_count($existing, "\n") + 1;
            $generatedLines = substr_count($contents, "\n") + 1;
            $this->error(sprintf(
                'Students-Profile.md is out of date at %s (existing: %d lines / %d bytes, generated: %d lines / %d bytes).',
                $path,
                $existingLines,
                strlen($existing),
                $generatedLines,
                strlen($contents),
            ));
        }

        return self::FAILURE;
    }

    private function stringOption(string $name): ?string
    {
        $value = $this->option($name);

        return is_string($value) && $value !== '' ? $value : null;
    }

    private function generateContents(): string
    {
        $sections = StudentRosterMap::sections();
        $roster = $this->buildRoster($sections);

        $lines = [
            ...$this->header(),
            '',
            ...$this->summarySection($sections),
            '',
            ...$this->rosterSection($sections, $roster),
            '',
            ...$this->footer($sections),
        ];

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    /** @return list<string> */
    private function header(): array
    {
        return [
            '# Students Profile',
            '',
            'Local test roster for the GRC enrollment system. Every account uses the password `password`',
            'and a grc.test email address. Generated by `php artisan students:generate-roster-file` —',
            'edit the command, not this file.',
        ];
    }

    /**
     * Assigns sequences per entry year in a stable order: college
     * (COE, CBAE, COA, CCS) -> year level ascending -> section code
     * ascending -> position within section. The sequence counter resets to
     * 1001 for each distinct entry year.
     *
     * @param  list<array{college: CollegeCode, program_code: string, section_code: string, year_level: int, size: int}>  $sections
     * @return array<string, list<array{student_number: string, email: string, name: string}>>
     */
    private function buildRoster(array $sections): array
    {
        $sequenceByEntryYear = [];
        $roster = [];

        foreach ($this->orderedSections($sections) as $section) {
            $entryYear = StudentRosterMap::entryYearFor($section['year_level']);
            $sequenceByEntryYear[$entryYear] ??= 1001;

            $rows = [];
            for ($position = 0; $position < $section['size']; $position++) {
                $rows[] = StudentIdentityGenerator::forIndex($entryYear, $sequenceByEntryYear[$entryYear]);
                $sequenceByEntryYear[$entryYear]++;
            }

            $roster[$this->sectionKey($section)] = $rows;
        }

        return $roster;
    }

    /**
     * Sections ordered college (COE, CBAE, COA, CCS) -> year level ascending
     * -> section code ascending. Shared by sequence assignment and roster
     * table layout so both walk the same deterministic order.
     *
     * @param  list<array{college: CollegeCode, program_code: string, section_code: string, year_level: int, size: int}>  $sections
     * @return list<array{college: CollegeCode, program_code: string, section_code: string, year_level: int, size: int}>
     */
    private function orderedSections(array $sections): array
    {
        $ordered = [];

        foreach (self::COLLEGE_ORDER as $college) {
            $collegeSections = array_values(array_filter(
                $sections,
                static fn (array $section): bool => $section['college'] === $college,
            ));
            usort(
                $collegeSections,
                static fn (array $a, array $b): int => [$a['year_level'], $a['section_code']] <=> [$b['year_level'], $b['section_code']],
            );
            array_push($ordered, ...$collegeSections);
        }

        return $ordered;
    }

    /** @param array{college: CollegeCode, program_code: string, section_code: string, year_level: int, size: int} $section */
    private function sectionKey(array $section): string
    {
        return $section['college']->value.'|'.$section['year_level'].'|'.$section['section_code'];
    }

    /**
     * @param  list<array{college: CollegeCode, program_code: string, section_code: string, year_level: int, size: int}>  $sections
     * @return list<string>
     */
    private function summarySection(array $sections): array
    {
        $aggregate = $this->aggregateByCollegeAndYear($sections);
        $lines = ['## Summary'];

        foreach (self::COLLEGE_ORDER as $college) {
            $lines[] = '';
            $lines[] = '### '.$college->label().' ('.strtoupper($college->value).')';
            $lines[] = '';
            array_push($lines, ...$this->perCollegeSummaryTable($college, $aggregate));
        }

        $lines[] = '';
        $lines[] = '### GRC Overall';
        $lines[] = '';
        array_push($lines, ...$this->overallSummaryTable($sections));

        $lines[] = '';
        $lines[] = '### Per-Department Summary';
        $lines[] = '';
        array_push($lines, ...$this->departmentSummaryTable($sections));

        return $lines;
    }

    /**
     * @param  list<array{college: CollegeCode, program_code: string, section_code: string, year_level: int, size: int}>  $sections
     * @return array<string, array<int, array{sections: int, students: int}>>
     */
    private function aggregateByCollegeAndYear(array $sections): array
    {
        $aggregate = [];

        foreach ($sections as $section) {
            $collegeKey = $section['college']->value;
            $year = $section['year_level'];
            $aggregate[$collegeKey][$year]['sections'] = ($aggregate[$collegeKey][$year]['sections'] ?? 0) + 1;
            $aggregate[$collegeKey][$year]['students'] = ($aggregate[$collegeKey][$year]['students'] ?? 0) + $section['size'];
        }

        return $aggregate;
    }

    /**
     * "Bilang" (Filipino for "count/tally") is the running cumulative
     * section count through each year level, distinct from the per-level
     * "Sections" and "Students" columns — e.g. a college with 8/8/7/4
     * sections across years 1-4 shows Bilang 8/16/23/27.
     *
     * @param  array<string, array<int, array{sections: int, students: int}>>  $aggregate
     * @return list<string>
     */
    private function perCollegeSummaryTable(CollegeCode $college, array $aggregate): array
    {
        $yearLevels = $aggregate[$college->value] ?? [];
        ksort($yearLevels);

        $rows = [];
        $totalSections = 0;
        $totalStudents = 0;
        $cumulativeSections = 0;

        foreach ($yearLevels as $year => $counts) {
            $cumulativeSections += $counts['sections'];
            $totalSections += $counts['sections'];
            $totalStudents += $counts['students'];
            $rows[] = [
                (string) $year,
                (string) $counts['sections'],
                (string) $cumulativeSections,
                number_format($counts['students']),
            ];
        }

        $rows[] = [
            '**Kabuuan**',
            '**'.$totalSections.'**',
            '**'.$cumulativeSections.'**',
            '**'.number_format($totalStudents).'**',
        ];

        return $this->alignedTable(
            ['Year Level', 'Sections', 'Bilang', 'Students'],
            $rows,
            [false, true, true, true],
        );
    }

    /**
     * @param  list<array{college: CollegeCode, program_code: string, section_code: string, year_level: int, size: int}>  $sections
     * @return list<string>
     */
    private function overallSummaryTable(array $sections): array
    {
        $byYear = [];
        foreach ($sections as $section) {
            $year = $section['year_level'];
            $byYear[$year]['sections'] = ($byYear[$year]['sections'] ?? 0) + 1;
            $byYear[$year]['students'] = ($byYear[$year]['students'] ?? 0) + $section['size'];
        }
        ksort($byYear);

        $rows = [];
        $totalSections = 0;
        $totalStudents = 0;
        foreach ($byYear as $year => $counts) {
            $totalSections += $counts['sections'];
            $totalStudents += $counts['students'];
            $rows[] = [(string) $year, (string) $counts['sections'], number_format($counts['students'])];
        }

        $rows[] = ['**Kabuuan**', '**'.$totalSections.'**', '**'.number_format($totalStudents).'**'];

        return $this->alignedTable(
            ['Year Level', 'Sections', 'Estimated Students'],
            $rows,
            [false, true, true],
        );
    }

    /**
     * A flat department-by-department total, deliberately not broken out by
     * year level — that breakdown already exists per-college above. Since
     * this codebase has no separate "department" concept, department is
     * treated as synonymous with college.
     *
     * @param  list<array{college: CollegeCode, program_code: string, section_code: string, year_level: int, size: int}>  $sections
     * @return list<string>
     */
    private function departmentSummaryTable(array $sections): array
    {
        $rows = [];
        $totalSections = 0;
        $totalStudents = 0;

        foreach (self::COLLEGE_ORDER as $college) {
            $collegeSections = array_filter(
                $sections,
                static fn (array $section): bool => $section['college'] === $college,
            );
            $sectionsCount = count($collegeSections);
            $studentsCount = array_sum(array_column($collegeSections, 'size'));
            $totalSections += $sectionsCount;
            $totalStudents += $studentsCount;
            $rows[] = [$college->label(), (string) $sectionsCount, number_format($studentsCount)];
        }

        $rows[] = ['**Kabuuan**', '**'.$totalSections.'**', '**'.number_format($totalStudents).'**'];

        return $this->alignedTable(
            ['Department', 'Sections', 'Students'],
            $rows,
            [false, true, true],
        );
    }

    /**
     * Renders a markdown table whose columns are padded to the widest cell
     * (header included) in that column, right-aligning numeric columns and
     * left-aligning label columns — matching the exact spacing convention
     * used throughout this file's summary tables.
     *
     * @param  list<string>  $headers
     * @param  list<list<string>>  $rows
     * @param  list<bool>  $rightAlign
     * @return list<string>
     */
    private function alignedTable(array $headers, array $rows, array $rightAlign): array
    {
        $widths = [];
        foreach ($headers as $index => $header) {
            $width = mb_strlen($header);
            foreach ($rows as $row) {
                $width = max($width, mb_strlen($row[$index]));
            }
            $widths[$index] = $width;
        }
        $widths = array_values($widths);

        $lines = [$this->alignedRow($headers, $widths, $rightAlign)];
        $lines[] = '|'.implode('|', array_map(
            static fn (int $width): string => str_repeat('-', $width + 2),
            $widths,
        )).'|';
        foreach ($rows as $row) {
            $lines[] = $this->alignedRow($row, $widths, $rightAlign);
        }

        return $lines;
    }

    /**
     * @param  list<string>  $cells
     * @param  list<int>  $widths
     * @param  list<bool>  $rightAlign
     */
    private function alignedRow(array $cells, array $widths, array $rightAlign): string
    {
        $rendered = [];
        foreach ($cells as $index => $cell) {
            $padded = str_pad($cell, $widths[$index], ' ', $rightAlign[$index] ? STR_PAD_LEFT : STR_PAD_RIGHT);
            $rendered[] = ' '.$padded.' ';
        }

        return '|'.implode('|', $rendered).'|';
    }

    /**
     * @param  list<array{college: CollegeCode, program_code: string, section_code: string, year_level: int, size: int}>  $sections
     * @param  array<string, list<array{student_number: string, email: string, name: string}>>  $roster
     * @return list<string>
     */
    private function rosterSection(array $sections, array $roster): array
    {
        $lines = [];
        $first = true;

        foreach (self::COLLEGE_ORDER as $college) {
            $collegeSections = array_values(array_filter(
                $sections,
                static fn (array $section): bool => $section['college'] === $college,
            ));
            usort(
                $collegeSections,
                static fn (array $a, array $b): int => [$a['year_level'], $a['section_code']] <=> [$b['year_level'], $b['section_code']],
            );

            $byYear = [];
            foreach ($collegeSections as $section) {
                $byYear[$section['year_level']][] = $section;
            }
            ksort($byYear);

            if (! $first) {
                $lines[] = '';
            }
            $first = false;
            $lines[] = '## '.$college->label();

            foreach ($byYear as $year => $yearSections) {
                $lines[] = '';
                $lines[] = '### Year '.$year;

                foreach ($yearSections as $section) {
                    $lines[] = '';
                    $lines[] = '#### '.$section['section_code'];
                    $lines[] = '';
                    $lines[] = '| Student No. | Name | Email | Program | Section | Year | Category |';
                    $lines[] = '|---|---|---|---|---|---|---|';

                    foreach ($roster[$this->sectionKey($section)] as $identity) {
                        $lines[] = sprintf(
                            '| %s | %s | %s | %s | %s | %d | Regular |',
                            $identity['student_number'],
                            $identity['name'],
                            $identity['email'],
                            $section['program_code'],
                            $section['section_code'],
                            $section['year_level'],
                        );
                    }
                }
            }
        }

        return $lines;
    }

    /**
     * @param  list<array{college: CollegeCode, program_code: string, section_code: string, year_level: int, size: int}>  $sections
     * @return list<string>
     */
    private function footer(array $sections): array
    {
        $totalSections = count($sections);
        $totalStudents = array_sum(array_column($sections, 'size'));

        return [
            '## Footer',
            '',
            "**Total sections:** {$totalSections}",
            '**Total students:** '.number_format($totalStudents),
            '',
            'Regenerate with `php artisan students:generate-roster-file` after any `StudentRosterMap` or',
            '`StudentIdentityGenerator` change — do not hand-edit this file. `Category` above is always',
            '`Regular` at generation time; it exists for human scanning only and is not authoritative grade evidence.',
        ];
    }

    private function guardEnvironment(): void
    {
        if (! app()->environment(['local', 'testing'])) {
            throw new RuntimeException('students:generate-roster-file may only run locally or in testing.');
        }
    }
}
