<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use RuntimeException;

/**
 * Cross-references the deterministic roster markdown file
 * (`Subject And Prerequisuite/Students-Profile.md`, generated by
 * `students:generate-roster-file`) against `student_profiles.enrollment_category`
 * in the database, and writes a companion file listing only the students the
 * real `ClassifyEnrollmentStanding` derived as Irregular.
 *
 * The roster file's own `Category` column is always `Regular` by design (see
 * `GenerateStudentRosterFile` — it is a pure, DB-free generator). Real
 * Regular/Irregular standing only exists once `StudentRosterSeeder` has
 * built real grade history and derived it, so this command requires that
 * seeder to have already run.
 */
final class GenerateIrregularStudentReport extends Command
{
    protected $signature = 'students:generate-irregular-report
        {--path= : Override the output file path (defaults to Subject And Prerequisuite/Irregular-Students.md at the project root)}
        {--roster-path= : Override the source roster file path (defaults to Subject And Prerequisuite/Students-Profile.md)}';

    protected $description = 'List every roster student the database has derived as Irregular, from real seeded grade history';

    private const DEFAULT_OUTPUT_PATH = __DIR__.'/../../../../Subject And Prerequisuite/Irregular-Students.md';

    private const DEFAULT_ROSTER_PATH = __DIR__.'/../../../../Subject And Prerequisuite/Students-Profile.md';

    private const STUDENT_NUMBER_PATTERN = '/^\d{4}-\d{2}-\d{5}$/';

    public function handle(): int
    {
        $this->guardEnvironment();

        $rosterPath = $this->stringOption('roster-path') ?? self::DEFAULT_ROSTER_PATH;
        $outputPath = $this->stringOption('path') ?? self::DEFAULT_OUTPUT_PATH;

        $rows = $this->parseRoster($rosterPath);
        $categoryByStudentNumber = $this->categoriesFor(array_column($rows, 'student_number'));

        if ($categoryByStudentNumber === []) {
            throw new RuntimeException(
                'No roster student numbers were found in student_profiles. Run StudentRosterSeeder '.
                '(php artisan db:seed --class=StudentRosterSeeder) before generating this report.',
            );
        }

        $irregular = array_values(array_filter(
            $rows,
            static fn (array $row): bool => ($categoryByStudentNumber[$row['student_number']] ?? null) === 'irregular',
        ));

        File::ensureDirectoryExists(dirname($outputPath));
        File::put($outputPath, $this->renderContents($irregular));
        $this->info("Wrote irregular student report to {$outputPath}.");

        return self::SUCCESS;
    }

    private function stringOption(string $name): ?string
    {
        $value = $this->option($name);

        return is_string($value) && $value !== '' ? $value : null;
    }

    /**
     * @param  list<string>  $studentNumbers
     * @return array<string, string>
     */
    private function categoriesFor(array $studentNumbers): array
    {
        if ($studentNumbers === []) {
            return [];
        }

        return DB::table('student_profiles')
            ->whereIn('student_number', $studentNumbers)
            ->whereNotNull('enrollment_category')
            ->pluck('enrollment_category', 'student_number')
            ->all();
    }

    /**
     * @param  list<array{student_number: string, name: string, email: string, program_code: string, section_code: string, year_level: int}>  $rows
     */
    private function renderContents(array $rows): string
    {
        $lines = [
            '# Irregular Students',
            '',
            'Generated by `php artisan students:generate-irregular-report` — edit the command, not this file.',
            'Cross-references `Subject And Prerequisuite/Students-Profile.md` against `student_profiles.enrollment_category`',
            'in the local database, derived by the real `ClassifyEnrollmentStanding` from actual seeded grade history',
            '(`Database\\Seeders\\StudentRosterSeeder`). A student appears here only when the database itself derived them',
            'as Irregular — never a guess.',
            '',
            '**Total irregular students:** '.count($rows),
            '',
            '| Student No. | Name | Email | Program | Section | Year |',
            '|---|---|---|---|---|---|',
        ];

        foreach ($rows as $row) {
            $lines[] = sprintf(
                '| %s | %s | %s | %s | %s | %d |',
                $row['student_number'],
                $row['name'],
                $row['email'],
                $row['program_code'],
                $row['section_code'],
                $row['year_level'],
            );
        }

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    /**
     * Parses only the `#### SECTION_CODE` roster tables, mirroring
     * `StudentRosterSeeder::parseRoster()` exactly — the `## Summary`
     * block's aggregate tables never carry a `Student No.` column, so a row
     * is only recognized when its first cell matches the `YYYY-NN-NNNNN`
     * student-number shape.
     *
     * @return list<array{student_number: string, name: string, email: string, program_code: string, section_code: string, year_level: int}>
     */
    private function parseRoster(string $path): array
    {
        if (! is_file($path)) {
            throw new RuntimeException("GenerateIrregularStudentReport could not find its roster file at {$path}");
        }

        $rows = [];
        $inSection = false;

        foreach (preg_split('/\R/u', File::get($path)) ?: [] as $line) {
            $trimmed = trim($line);

            if (str_starts_with($trimmed, '#### ')) {
                $inSection = true;

                continue;
            }

            if (str_starts_with($trimmed, '#')) {
                $inSection = false;

                continue;
            }

            if (! $inSection || $trimmed === '' || ! str_starts_with($trimmed, '|')) {
                continue;
            }

            $cells = array_map('trim', explode('|', trim($trimmed, '|')));
            if (count($cells) !== 7 || preg_match(self::STUDENT_NUMBER_PATTERN, $cells[0]) !== 1) {
                continue;
            }

            $rows[] = [
                'student_number' => $cells[0],
                'name' => $cells[1],
                'email' => $cells[2],
                'program_code' => $cells[3],
                'section_code' => $cells[4],
                'year_level' => (int) $cells[5],
            ];
        }

        return $rows;
    }

    private function guardEnvironment(): void
    {
        if (! app()->environment(['local', 'testing'])) {
            throw new RuntimeException('students:generate-irregular-report may only run locally or in testing.');
        }
    }
}
