<?php

namespace Database\Seeders;

use App\Domain\Identity\AcademicStanding;
use App\Domain\Identity\AdmissionStatus;
use App\Domain\Identity\UserRole;
use App\Domain\Identity\UserStatus;
use App\Domain\Organization\StudentRosterMap;
use App\Models\Curriculum;
use App\Models\Program;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use RuntimeException;

/**
 * Turns the deterministic local roster markdown file generated by
 * `php artisan students:generate-roster-file` (see
 * `App\Console\Commands\GenerateStudentRosterFile` and
 * `App\Domain\Organization\StudentRosterMap`) into real `users` +
 * `student_profiles` accounts — 3,210 students across 107 sections at the
 * roster's current size.
 *
 * Only the `#### SECTION_CODE` roster tables are parsed. The `## Summary`
 * block at the top of the file (per-college, GRC-overall, and
 * per-department aggregate tables) is deliberately skipped — those tables
 * never carry a `Student No.` column, so a row is only recognized when its
 * first cell matches the `YYYY-NN-NNNNN` student-number shape.
 *
 * This is deliberately accounts-only: enrollment/grade history, the
 * regular/irregular derivation, and demand observations are seeded by later
 * tasks in the same plan, not here. `enrollment_category` is always left
 * null, the same seed-only sentinel `DemoEnrollmentSeeder` uses until a real
 * classifier run derives it.
 *
 * Depends on `ProgramSeeder` and `GrcCurriculumSeeder` having already run —
 * every program code in the roster must resolve to a seeded `Program`, and
 * that program must have exactly one `active` curriculum (the 2024-2029
 * version; `GrcCurriculumSeeder` only ever marks one version per program as
 * `active`, the two older versions are `archived`).
 */
final class StudentRosterSeeder extends Seeder
{
    private const DEFAULT_PATH = __DIR__.'/../../../Subject And Prerequisuite/Students-Profile.md';

    private const PASSWORD = 'password';

    private const CHUNK_SIZE = 500;

    private const STUDENT_NUMBER_PATTERN = '/^\d{4}-\d{2}-\d{5}$/';

    public function __construct(private readonly ?string $rosterPath = null) {}

    public function run(): void
    {
        $this->guardEnvironment();

        $path = $this->resolveRosterPath();
        if ($path === null) {
            return;
        }

        $rows = $this->parseRoster($path);
        if ($rows === []) {
            return;
        }

        $programIdByCode = $this->programIdsByCode($rows);
        $curriculumIdByProgramId = $this->activeCurriculumIdsByProgramId($programIdByCode);
        $passwordHash = Hash::make(self::PASSWORD);
        $now = now();

        foreach (array_chunk($rows, self::CHUNK_SIZE) as $chunk) {
            $this->upsertChunk($chunk, $programIdByCode, $curriculumIdByProgramId, $passwordHash, $now);
        }
    }

    /**
     * @param  list<array{student_number: string, name: string, email: string, program_code: string, year_level: int}>  $chunk
     * @param  array<string, int>  $programIdByCode
     * @param  array<int, int>  $curriculumIdByProgramId
     */
    private function upsertChunk(
        array $chunk,
        array $programIdByCode,
        array $curriculumIdByProgramId,
        string $passwordHash,
        Carbon $now,
    ): void {
        $userRows = [];
        foreach ($chunk as $row) {
            $userRows[] = [
                'name' => $row['name'],
                'email' => $row['email'],
                'password' => $passwordHash,
                'role' => UserRole::Student->value,
                'status' => UserStatus::Active->value,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        DB::table('users')->upsert(
            $userRows,
            ['email'],
            ['name', 'password', 'role', 'status', 'updated_at'],
        );

        $emails = array_column($chunk, 'email');
        $userIdByEmail = DB::table('users')->whereIn('email', $emails)->pluck('id', 'email');

        $profileRows = [];
        foreach ($chunk as $row) {
            $programId = $programIdByCode[$row['program_code']]
                ?? throw new RuntimeException("StudentRosterSeeder found no seeded program for code '{$row['program_code']}'. Run ProgramSeeder first.");
            $curriculumId = $curriculumIdByProgramId[$programId]
                ?? throw new RuntimeException("StudentRosterSeeder found no active curriculum for program '{$row['program_code']}'. Run GrcCurriculumSeeder first.");
            $userId = $userIdByEmail[$row['email']]
                ?? throw new RuntimeException("StudentRosterSeeder could not resolve the user just upserted for '{$row['email']}'.");

            $profileRows[] = [
                'user_id' => $userId,
                'student_number' => $row['student_number'],
                'program_id' => $programId,
                'curriculum_id' => $curriculumId,
                'entry_year' => StudentRosterMap::entryYearFor($row['year_level']),
                'year_level' => $row['year_level'],
                'admission_status' => AdmissionStatus::Admitted->value,
                'academic_standing' => AcademicStanding::Good->value,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        DB::table('student_profiles')->upsert(
            $profileRows,
            ['student_number'],
            ['user_id', 'program_id', 'curriculum_id', 'entry_year', 'year_level', 'admission_status', 'academic_standing', 'updated_at'],
        );
    }

    /**
     * @param  list<array{student_number: string, name: string, email: string, program_code: string, year_level: int}>  $rows
     * @return array<string, int>
     */
    private function programIdsByCode(array $rows): array
    {
        $codes = array_values(array_unique(array_column($rows, 'program_code')));

        return Program::query()->whereIn('code', $codes)->pluck('id', 'code')->all();
    }

    /**
     * Assumes exactly one `active` curriculum per program — true by
     * construction of `GrcCurriculumSeeder`, which marks only the
     * 2024-2029 version `active` and both older versions `archived`.
     *
     * @param  array<string, int>  $programIdByCode
     * @return array<int, int>
     */
    private function activeCurriculumIdsByProgramId(array $programIdByCode): array
    {
        return Curriculum::query()
            ->whereIn('program_id', array_values($programIdByCode))
            ->where('status', 'active')
            ->pluck('id', 'program_id')
            ->all();
    }

    /**
     * The full 3,210-row roster is real local/dev fixture data, not
     * something every unrelated test that happens to run the whole
     * `DatabaseSeeder` chain (e.g. `DemoEnrollmentSeederTest`) should pay
     * for or assert around. The same problem already exists for
     * `WorkbookFacultyProfileSeeder`'s `Professor_Department_List.md`, and
     * this follows its exact fix: the real default path is only used in the
     * `local` environment. An explicit constructor path (what every test of
     * this seeder itself passes) always wins, in any environment.
     */
    private function resolveRosterPath(): ?string
    {
        if ($this->rosterPath !== null) {
            return $this->rosterPath;
        }

        return app()->environment('local') && is_file(self::DEFAULT_PATH)
            ? self::DEFAULT_PATH
            : null;
    }

    /**
     * Parses only the `#### SECTION_CODE` roster tables out of the roster
     * markdown file. A line is treated as roster data only while inside a
     * section opened by a `#### ` heading, AND its first table cell matches
     * the `YYYY-NN-NNNNN` student-number shape — this is what naturally
     * excludes the `## Summary` block's aggregate tables (none of their
     * rows carry a student number in that shape) without needing to parse
     * headings at all beyond tracking "are we inside a `####` section".
     *
     * @return list<array{student_number: string, name: string, email: string, program_code: string, year_level: int}>
     */
    private function parseRoster(string $path): array
    {
        if (! is_file($path)) {
            throw new RuntimeException("StudentRosterSeeder could not find its roster file at {$path}");
        }

        $rows = [];
        $inSection = false;

        foreach (preg_split('/\R/u', File::get($path)) ?: [] as $line) {
            $trimmed = trim($line);

            if (str_starts_with($trimmed, '#### ')) {
                $inSection = true;

                continue;
            }

            if (str_starts_with($trimmed, '#')) {
                $inSection = false;

                continue;
            }

            if (! $inSection || $trimmed === '' || ! str_starts_with($trimmed, '|')) {
                continue;
            }

            $cells = array_map('trim', explode('|', trim($trimmed, '|')));
            if (count($cells) !== 7 || preg_match(self::STUDENT_NUMBER_PATTERN, $cells[0]) !== 1) {
                continue;
            }

            $rows[] = [
                'student_number' => $cells[0],
                'name' => $cells[1],
                'email' => $cells[2],
                'program_code' => $cells[3],
                'year_level' => (int) $cells[5],
            ];
        }

        return $rows;
    }

    private function guardEnvironment(): void
    {
        if (! app()->environment(['local', 'testing'])) {
            throw new RuntimeException('StudentRosterSeeder may only run locally or in testing.');
        }
    }
}
