<?php

namespace Database\Seeders;

use App\Domain\Faculty\SpecializationProficiency;
use App\Domain\Identity\AcademicStanding;
use App\Domain\Identity\AdmissionStatus;
use App\Domain\Identity\UserRole;
use App\Domain\Identity\UserStatus;
use App\Domain\Organization\CapacitySource;
use App\Domain\Organization\CollegeCode;
use App\Domain\Organization\SectionBlockCode;
use App\Domain\Organization\SectionPlanStatus;
use App\Domain\Organization\StudentRosterMap;
use App\Domain\Scheduling\SectionStatus;
use App\Models\AcademicTerm;
use App\Models\Curriculum;
use App\Models\CurriculumSubject;
use App\Models\Program;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use RuntimeException;

/**
 * Turns the deterministic local roster markdown file generated by
 * `php artisan students:generate-roster-file` (see
 * `App\Console\Commands\GenerateStudentRosterFile` and
 * `App\Domain\Organization\StudentRosterMap`) into real `users` +
 * `student_profiles` accounts — 3,210 students across 107 sections at the
 * roster's current size.
 *
 * Only the `#### SECTION_CODE` roster tables are parsed. The `## Summary`
 * block at the top of the file (per-college, GRC-overall, and
 * per-department aggregate tables) is deliberately skipped — those tables
 * never carry a `Student No.` column, so a row is only recognized when its
 * first cell matches the `YYYY-NN-NNNNN` student-number shape.
 *
 * This is deliberately accounts-only: enrollment/grade history, the
 * regular/irregular derivation, and demand observations are seeded by later
 * tasks in the same plan, not here. `enrollment_category` is always left
 * null, the same seed-only sentinel `DemoEnrollmentSeeder` uses until a real
 * classifier run derives it.
 *
 * Depends on `ProgramSeeder` and `GrcCurriculumSeeder` having already run —
 * every program code in the roster must resolve to a seeded `Program`, and
 * that program must have exactly one `active` curriculum (the 2024-2029
 * version; `GrcCurriculumSeeder` only ever marks one version per program as
 * `active`, the two older versions are `archived`).
 */
final class StudentRosterSeeder extends Seeder
{
    private const DEFAULT_PATH = __DIR__.'/../../../Subject And Prerequisuite/Students-Profile.md';

    private const PASSWORD = 'password';

    private const CHUNK_SIZE = 500;

    private const STUDENT_NUMBER_PATTERN = '/^\d{4}-\d{2}-\d{5}$/';

    private const SECTION_CHUNK_SIZE = 1000;

    /**
     * Every block — real or synthetic — caps at 40 seats. Historical block
     * *counts* are derived from this same number (`ceil(headcount / 40)`),
     * see `historicalBlocks()`.
     */
    private const BLOCK_CAPACITY = 40;

    /** @var list<string> */
    private const SCHEDULE_DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

    /** @var list<array{0: string, 1: string}> */
    private const TIME_SLOTS = [
        ['08:00:00', '10:00:00'],
        ['10:00:00', '12:00:00'],
        ['13:00:00', '15:00:00'],
        ['15:00:00', '17:00:00'],
    ];

    /** Total distinct (day, time) combinations professor slot-cycling can try. */
    private const SLOT_COUNT = 24;

    /**
     * Professor round-robin cursor, keyed by "{subject_id}|{college}" ->
     * index into that key's ordered candidate list. Rebuilt fresh on every
     * `run()` call so reruns are deterministic.
     *
     * @var array<string, int>
     */
    private array $professorCursor = [];

    /**
     * Which professors are already booked at a given (term, day, start
     * time) slot, so the same professor is never handed two sections that
     * overlap. Keyed by "{term_id}:{day}:{start}" -> {professor_id: true}.
     *
     * @var array<string, array<int, true>>
     */
    private array $bookedSlots = [];

    /** @var array<string, list<int>> */
    private array $professorCandidateCache = [];

    /** @var array<string, Collection<int, CurriculumSubject>> */
    private array $curriculumSubjectCache = [];

    public function __construct(private readonly ?string $rosterPath = null) {}

    public function run(): void
    {
        $this->guardEnvironment();

        $path = $this->resolveRosterPath();
        if ($path === null) {
            return;
        }

        $rows = $this->parseRoster($path);
        if ($rows === []) {
            return;
        }

        $programIdByCode = $this->programIdsByCode($rows);
        $curriculumIdByProgramId = $this->activeCurriculumIdsByProgramId($programIdByCode);
        $passwordHash = Hash::make(self::PASSWORD);
        $now = now();

        foreach (array_chunk($rows, self::CHUNK_SIZE) as $chunk) {
            $this->upsertChunk($chunk, $programIdByCode, $curriculumIdByProgramId, $passwordHash, $now);
        }

        $this->seedSectionHistory();
    }

    /**
     * @param  list<array{student_number: string, name: string, email: string, program_code: string, year_level: int}>  $chunk
     * @param  array<string, int>  $programIdByCode
     * @param  array<int, int>  $curriculumIdByProgramId
     */
    private function upsertChunk(
        array $chunk,
        array $programIdByCode,
        array $curriculumIdByProgramId,
        string $passwordHash,
        Carbon $now,
    ): void {
        $userRows = [];
        foreach ($chunk as $row) {
            $userRows[] = [
                'name' => $row['name'],
                'email' => $row['email'],
                'password' => $passwordHash,
                'role' => UserRole::Student->value,
                'status' => UserStatus::Active->value,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        DB::table('users')->upsert(
            $userRows,
            ['email'],
            ['name', 'password', 'role', 'status', 'updated_at'],
        );

        $emails = array_column($chunk, 'email');
        $userIdByEmail = DB::table('users')->whereIn('email', $emails)->pluck('id', 'email');

        $profileRows = [];
        foreach ($chunk as $row) {
            $programId = $programIdByCode[$row['program_code']]
                ?? throw new RuntimeException("StudentRosterSeeder found no seeded program for code '{$row['program_code']}'. Run ProgramSeeder first.");
            $curriculumId = $curriculumIdByProgramId[$programId]
                ?? throw new RuntimeException("StudentRosterSeeder found no active curriculum for program '{$row['program_code']}'. Run GrcCurriculumSeeder first.");
            $userId = $userIdByEmail[$row['email']]
                ?? throw new RuntimeException("StudentRosterSeeder could not resolve the user just upserted for '{$row['email']}'.");

            $profileRows[] = [
                'user_id' => $userId,
                'student_number' => $row['student_number'],
                'program_id' => $programId,
                'curriculum_id' => $curriculumId,
                'entry_year' => StudentRosterMap::entryYearFor($row['year_level']),
                'year_level' => $row['year_level'],
                'admission_status' => AdmissionStatus::Admitted->value,
                'academic_standing' => AcademicStanding::Good->value,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        DB::table('student_profiles')->upsert(
            $profileRows,
            ['student_number'],
            ['user_id', 'program_id', 'curriculum_id', 'entry_year', 'year_level', 'admission_status', 'academic_standing', 'updated_at'],
        );
    }

    /**
     * Builds `academic_term_section_plans` + `sections` history for every
     * `StudentRosterMap` block across all seven academic terms.
     *
     * `StudentRosterMap::sections()` is a static structural catalog of the
     * 107 blocks GRC currently runs, independent of which specific roster
     * rows were parsed above — it always describes the full current-term
     * shape, so a cohort walked backwards can reconstruct history even
     * against a trimmed test roster.
     *
     * Grouping the map's rows by (college, program, year_level) recovers
     * one "cohort" per group: the population currently sitting at that
     * year level in that program, along with its real total headcount (the
     * sum of `size` across that group's blocks — this data model has no
     * attrition, so a cohort's headcount is the same in every one of its
     * years). Each cohort entered in the year `StudentRosterMap::entryYearFor()`
     * reports for its year level, so its position in any of the seven terms
     * is `currentYearLevel - academic years elapsed since that term`.
     *
     * Only the *current* term ("today", academic-year-elapsed = 0) reflects
     * the real, already-known block codes from the map. Every earlier term
     * for that same cohort has no known historical block *assignment*, but
     * its headcount is still known (same as today's, no attrition), so it
     * gets `ceil(headcount / 40)` synthetic representative blocks —
     * `SectionBlockCode::fromProgram(..., blockOrdinal: 1..N)` — the same
     * scale a real cohort of that size would have needed. The roster's own
     * verbatim `EDUC1xx` codes (which `fromProgram()` cannot reproduce —
     * see `coePrefix()`) are a one-time naming artifact of the real
     * *current* COE year-1 intake specifically, so they are only ever used
     * via the `$isToday` branch below (reading `$cohort['blocks']`
     * straight from the map) — never projected onto a different cohort's
     * own historical year-1 term, which uses normal `fromProgram()` naming
     * like any other college/year combination.
     *
     * Two cohorts of the same program never collide on a (term, computed
     * year level) pair (they differ in current year level, so their
     * projected year levels in any shared term differ too), so this never
     * produces two different block lists for the same
     * (term, section_code, subject) key.
     */
    private function seedSectionHistory(): void
    {
        $terms = $this->orderedTerms();
        if ($terms === []) {
            return;
        }

        $currentStartYear = max(array_column($terms, 'start_year'));

        $cohorts = $this->cohortsFromRosterMap();
        if ($cohorts === []) {
            return;
        }

        $programCodes = array_values(array_unique(array_column($cohorts, 'program_code')));
        $programIdByCode = Program::query()->whereIn('code', $programCodes)->pluck('id', 'code')->all();
        $curriculumIdByProgramId = $this->activeCurriculumIdsByProgramId($programIdByCode);

        $roomsByCollege = $this->roomsByCollege();
        $this->preloadProfessorCandidates();

        $now = now();
        $planRows = [];
        $planKeys = [];

        // Pass 1: compute every (term, cohort) contribution and the plan
        // row it belongs to, without touching professors yet — the plan
        // must exist (and its id be known) before any `sections` row can
        // reference `section_plan_id`. Subjects ARE resolved here (not
        // deferred to pass 2) so a (curriculum, year_level, semester) with
        // zero curriculum subjects is skipped entirely — no plan row and no
        // sections — rather than writing a plan row whose `section_count`
        // would overstate a `sections` count of zero.
        $contributions = [];
        foreach ($cohorts as $cohort) {
            $programId = $programIdByCode[$cohort['program_code']] ?? null;
            $curriculumId = $programId !== null ? ($curriculumIdByProgramId[$programId] ?? null) : null;
            if ($curriculumId === null) {
                // Program not seeded in this environment/test — StudentRosterMap
                // is a static catalog of the *real* production block shape and
                // deliberately outruns any single test's minimal fixture.
                continue;
            }

            foreach ($terms as $term) {
                $academicYearsElapsed = $currentStartYear - $term['start_year'];
                $yearLevel = $cohort['year_level'] - $academicYearsElapsed;
                if ($yearLevel < 1 || $yearLevel > $cohort['year_level']) {
                    continue;
                }

                $isToday = $academicYearsElapsed === 0;
                $blocks = $isToday
                    ? $cohort['blocks']
                    : $this->historicalBlocks($cohort['program_code'], $cohort['college'], $yearLevel, $cohort['headcount']);

                $subjects = $this->curriculumSubjectsFor($curriculumId, $yearLevel, $term['semester']);
                if ($subjects->isEmpty()) {
                    continue;
                }

                $planKey = implode('|', [$term['id'], $curriculumId, $cohort['college']->value, $yearLevel]);
                if (! isset($planKeys[$planKey])) {
                    $planKeys[$planKey] = true;
                    $planRows[] = [
                        'academic_term_id' => $term['id'],
                        'curriculum_id' => $curriculumId,
                        'college' => $cohort['college']->value,
                        'year_level' => $yearLevel,
                        'section_count' => count($blocks),
                        'status' => SectionPlanStatus::Submitted->value,
                        'created_at' => $now,
                        'updated_at' => $now,
                    ];
                }

                $contributions[] = [
                    'term' => $term,
                    'curriculum_id' => $curriculumId,
                    'college' => $cohort['college'],
                    'year_level' => $yearLevel,
                    'semester' => $term['semester'],
                    'plan_key' => $planKey,
                    'blocks' => $blocks,
                    'subjects' => $subjects,
                ];
            }
        }

        if ($planRows === []) {
            return;
        }

        foreach (array_chunk($planRows, self::SECTION_CHUNK_SIZE) as $chunk) {
            DB::table('academic_term_section_plans')->upsert(
                $chunk,
                ['academic_term_id', 'curriculum_id', 'college', 'year_level'],
                ['section_count', 'status', 'updated_at'],
            );
        }

        $planIdByKey = $this->planIdsByKey(array_keys($planKeys));

        // Pass 2: now that every plan id is known, expand each contribution
        // into one `sections` row per (block, subject).
        $sectionRows = [];
        foreach ($contributions as $contribution) {
            $planId = $planIdByKey[$contribution['plan_key']] ?? null;

            foreach ($contribution['blocks'] as $blockCode) {
                foreach ($contribution['subjects'] as $curriculumSubject) {
                    $subjectId = $curriculumSubject->subject_id;
                    $room = $this->deterministicRoom($contribution['college'], $contribution['term']['id'], $blockCode, $subjectId, $roomsByCollege);
                    [$professorId, $day, $starts, $ends] = $this->pickProfessor(
                        $subjectId,
                        $contribution['curriculum_id'],
                        $contribution['college'],
                        $contribution['term']['id'],
                        $blockCode,
                    );

                    $sectionRows[] = [
                        'academic_term_id' => $contribution['term']['id'],
                        'section_plan_id' => $planId,
                        'subject_id' => $subjectId,
                        'section_code' => $blockCode,
                        'professor_id' => $professorId,
                        'schedule_days' => $day,
                        'starts_at_time' => $starts,
                        'ends_at_time' => $ends,
                        'room' => $room,
                        'capacity' => self::BLOCK_CAPACITY,
                        'capacity_source' => CapacitySource::Plan->value,
                        'is_block_exclusive' => true,
                        'status' => SectionStatus::Closed->value,
                        'created_at' => $now,
                        'updated_at' => $now,
                    ];
                }
            }
        }

        foreach (array_chunk($sectionRows, self::SECTION_CHUNK_SIZE) as $chunk) {
            DB::table('sections')->upsert(
                $chunk,
                ['academic_term_id', 'subject_id', 'section_code'],
                [
                    'section_plan_id', 'professor_id', 'schedule_days', 'starts_at_time', 'ends_at_time',
                    'room', 'capacity', 'capacity_source', 'is_block_exclusive', 'status', 'updated_at',
                ],
            );
        }
    }

    /**
     * All seven `AcademicTermSeeder` terms, oldest first, with a parsed
     * academic-year start for computing "how many academic years ago".
     *
     * @return list<array{id: int, school_year: string, semester: string, start_year: int}>
     */
    private function orderedTerms(): array
    {
        $terms = AcademicTerm::query()
            ->get(['id', 'school_year', 'semester'])
            ->map(fn (AcademicTerm $term): array => [
                'id' => $term->id,
                'school_year' => $term->school_year,
                'semester' => $term->semester,
                'start_year' => (int) substr($term->school_year, 0, 4),
            ])
            ->all();

        usort($terms, fn (array $a, array $b): int => $a['start_year'] <=> $b['start_year']
            ?: ($a['semester'] === $b['semester'] ? 0 : ($a['semester'] === '1st' ? -1 : 1)));

        return $terms;
    }

    /**
     * Groups `StudentRosterMap::sections()` rows into the 41 (college,
     * program, current-year-level) cohorts, sorted deterministically so
     * professor round-robin assignment is reproducible across reruns.
     * `headcount` is the sum of every block's `size` in the group — the
     * cohort's real total population, reused as-is for every one of its
     * historical terms since this data model has no attrition.
     *
     * @return list<array{college: CollegeCode, program_code: string, year_level: int, blocks: list<string>, headcount: int}>
     */
    private function cohortsFromRosterMap(): array
    {
        $cohorts = [];
        foreach (StudentRosterMap::sections() as $row) {
            $key = $row['college']->value.'|'.$row['program_code'].'|'.$row['year_level'];
            $cohorts[$key]['college'] ??= $row['college'];
            $cohorts[$key]['program_code'] ??= $row['program_code'];
            $cohorts[$key]['year_level'] ??= $row['year_level'];
            $cohorts[$key]['blocks'][] = $row['section_code'];
            $cohorts[$key]['headcount'] = ($cohorts[$key]['headcount'] ?? 0) + $row['size'];
        }

        $cohorts = array_values($cohorts);
        usort($cohorts, fn (array $a, array $b): int => [$a['college']->value, $a['program_code'], $a['year_level']]
            <=> [$b['college']->value, $b['program_code'], $b['year_level']]);

        return $cohorts;
    }

    /**
     * `ceil(headcount / 40)` synthetic historical blocks for a cohort's
     * projected year level in a term before "today", ordinals 1..N via
     * `SectionBlockCode::fromProgram()` — the same naming `seedSectionHistory()`
     * already uses for the ordinal-1 block, just carried through however
     * many blocks the cohort's real headcount needs.
     *
     * Deliberately does NOT special-case COE year 1's verbatim `EDUC1xx`
     * codes: those are a one-time naming artifact of the real *current*
     * COE year-1 intake (handled by the `$isToday` branch in
     * `seedSectionHistory()`, which reads `StudentRosterMap` codes
     * directly) and were never actually assigned to any other cohort's own
     * historical freshman year — a different cohort's year-1 projection
     * uses normal per-program naming (`ELEM101`, `FIL101`, `ENG101`,
     * `SOCSCI101`, `VAL101`, ...) like any other college/year combination.
     *
     * @return list<string>
     */
    private function historicalBlocks(string $programCode, CollegeCode $college, int $yearLevel, int $headcount): array
    {
        $blockCount = max(1, (int) ceil($headcount / self::BLOCK_CAPACITY));

        $blocks = [];
        for ($ordinal = 1; $ordinal <= $blockCount; $ordinal++) {
            $blocks[] = SectionBlockCode::fromProgram($programCode, $college, $yearLevel, $ordinal);
        }

        return $blocks;
    }

    /**
     * @param  list<string>  $keys
     * @return array<string, int>
     */
    private function planIdsByKey(array $keys): array
    {
        $planIdByKey = array_fill_keys($keys, null);

        DB::table('academic_term_section_plans')
            ->select(['id', 'academic_term_id', 'curriculum_id', 'college', 'year_level'])
            ->get()
            ->each(function (object $plan) use (&$planIdByKey): void {
                $key = implode('|', [$plan->academic_term_id, $plan->curriculum_id, $plan->college, $plan->year_level]);
                if (array_key_exists($key, $planIdByKey)) {
                    $planIdByKey[$key] = $plan->id;
                }
            });

        return $planIdByKey;
    }

    /**
     * `curriculum_subjects.semester` is either a plain `'1st'`/`'2nd'` or
     * the composite `'1st|2nd'` written for subjects offered either
     * semester (see `SemesterCoverage`) — both must match a query for
     * either single semester.
     *
     * @return Collection<int, CurriculumSubject>
     */
    private function curriculumSubjectsFor(int $curriculumId, int $yearLevel, string $semester): Collection
    {
        $cacheKey = $curriculumId.'|'.$yearLevel.'|'.$semester;

        return $this->curriculumSubjectCache[$cacheKey] ??= CurriculumSubject::query()
            ->where('curriculum_id', $curriculumId)
            ->where('year_level', $yearLevel)
            ->where(function ($query) use ($semester): void {
                $query->where('semester', $semester)->orWhere('semester', '1st|2nd');
            })
            ->orderBy('subject_id')
            ->get();
    }

    /** @return array<string, list<string>> */
    private function roomsByCollege(): array
    {
        $rooms = [];
        foreach (DB::table('room_catalog_entries')->orderBy('id')->get(['college', 'name']) as $entry) {
            $rooms[(string) $entry->college][] = (string) $entry->name;
        }

        return $rooms;
    }

    /**
     * Deterministic, hash-derived *base* slot index (0..23) for a section —
     * stable across reruns because it only depends on stable identifiers
     * (the term id, the block's section code, and the subject id), never on
     * insertion order or randomness. `pickProfessor()` starts its slot
     * search here and cycles forward through `slotAt()` if the professor
     * pool is already booked at this slot.
     */
    private function deterministicSlotIndex(int $termId, string $blockCode, int $subjectId): int
    {
        $hash = (int) sprintf('%u', crc32($termId.':'.$blockCode.':'.$subjectId));

        return $hash % self::SLOT_COUNT;
    }

    /**
     * Resolves a slot index (0..23) into its (day, starts, ends) triple.
     * `self::SLOT_COUNT` (24) must equal
     * `count(SCHEDULE_DAYS) * count(TIME_SLOTS)` (6 * 4) for this mapping
     * to cover every combination exactly once.
     *
     * @return array{0: string, 1: string, 2: string}
     */
    private function slotAt(int $slotIndex): array
    {
        $day = self::SCHEDULE_DAYS[$slotIndex % count(self::SCHEDULE_DAYS)];
        [$starts, $ends] = self::TIME_SLOTS[intdiv($slotIndex, count(self::SCHEDULE_DAYS)) % count(self::TIME_SLOTS)];

        return [$day, $starts, $ends];
    }

    /** @param  array<string, list<string>>  $roomsByCollege */
    private function deterministicRoom(CollegeCode $college, int $termId, string $blockCode, int $subjectId, array $roomsByCollege): ?string
    {
        $rooms = $roomsByCollege[$college->value] ?? [];
        if ($rooms === []) {
            return null;
        }

        $hash = (int) sprintf('%u', crc32('room:'.$termId.':'.$blockCode.':'.$subjectId));

        return $rooms[$hash % count($rooms)];
    }

    /**
     * Preloads every candidate ordering this seeder will ever need for
     * professor assignment, so picking a professor for one of potentially
     * thousands of `sections` rows never issues its own query.
     */
    private function preloadProfessorCandidates(): void
    {
        $this->professorCandidateCache = [];

        $specialists = DB::table('faculty_specializations')
            ->join('users', 'users.id', '=', 'faculty_specializations.professor_id')
            ->where('faculty_specializations.proficiency', SpecializationProficiency::Primary->value)
            ->where('users.role', UserRole::Faculty->value)
            ->whereNotNull('users.college')
            ->orderBy('faculty_specializations.professor_id')
            ->get(['faculty_specializations.subject_id', 'users.college', 'faculty_specializations.professor_id']);

        foreach ($specialists as $row) {
            $key = 'specialist|'.$row->subject_id.'|'.$row->college;
            $this->professorCandidateCache[$key][] = (int) $row->professor_id;
        }

        // College-scoped, matching tier 1 and tier 3: nothing enforces
        // within-college preferences at the API level
        // (`CreateFacultyCurriculumSubjectPreference` has no such
        // validation), so a cross-college preference row must never leak
        // into a different college's candidate pool here.
        $preferences = DB::table('faculty_curriculum_subject_preferences')
            ->join('users', 'users.id', '=', 'faculty_curriculum_subject_preferences.professor_id')
            ->where('users.role', UserRole::Faculty->value)
            ->whereNotNull('users.college')
            ->orderBy('faculty_curriculum_subject_preferences.rank')
            ->orderBy('faculty_curriculum_subject_preferences.professor_id')
            ->get(['faculty_curriculum_subject_preferences.curriculum_id', 'faculty_curriculum_subject_preferences.subject_id', 'users.college', 'faculty_curriculum_subject_preferences.professor_id']);

        foreach ($preferences as $row) {
            $key = 'preference|'.$row->curriculum_id.'|'.$row->subject_id.'|'.$row->college;
            $this->professorCandidateCache[$key][] = (int) $row->professor_id;
        }

        $facultyByCollege = DB::table('users')
            ->where('role', UserRole::Faculty->value)
            ->whereNotNull('college')
            ->orderBy('id')
            ->get(['id', 'college']);

        foreach ($facultyByCollege as $row) {
            $key = 'any|'.$row->college;
            $this->professorCandidateCache[$key][] = (int) $row->id;
        }
    }

    /**
     * Ordered, deduplicated professor candidates for a (subject,
     * curriculum, college): `primary` specialists first, then reusable
     * curriculum preferences, then any faculty in the section's college —
     * exactly the fallback chain the brief specifies.
     *
     * @return list<int>
     */
    private function professorCandidates(int $subjectId, int $curriculumId, CollegeCode $college): array
    {
        $cacheKey = 'candidates|'.$subjectId.'|'.$curriculumId.'|'.$college->value;
        if (isset($this->professorCandidateCache[$cacheKey])) {
            return $this->professorCandidateCache[$cacheKey];
        }

        $tiers = array_merge(
            $this->professorCandidateCache['specialist|'.$subjectId.'|'.$college->value] ?? [],
            $this->professorCandidateCache['preference|'.$curriculumId.'|'.$subjectId.'|'.$college->value] ?? [],
            $this->professorCandidateCache['any|'.$college->value] ?? [],
        );

        return $this->professorCandidateCache[$cacheKey] = array_values(array_unique($tiers));
    }

    /**
     * Round-robins through the ordered candidate list for this
     * (subject, college) so the load spreads across every eligible
     * professor instead of always picking the first. Starts at the
     * deterministic base slot (`deterministicSlotIndex()`) and, if every
     * candidate is already booked there, cycles forward through the
     * remaining `SLOT_COUNT` (24) day/time combinations looking for one
     * where some eligible candidate is free — the section's own
     * schedule_days/starts_at_time/ends_at_time move to whichever slot the
     * professor was actually booked at, so the two are never
     * inconsistent. Only double-books (last resort) if every
     * (candidate × slot) combination is exhausted, and even then throws
     * rather than silently double-booking — matching this codebase's
     * "local/testing only, throw on broken invariant" convention for
     * seeders (see `guardEnvironment()`), since silent data corruption in a
     * scheduling seeder is worse than a loud failure telling you the
     * candidate pool or slot space is too small.
     *
     * Also throws immediately if the (subject, curriculum, college) has no
     * eligible candidates at all — the brief's hard requirement ("every
     * historical section has a professor") must never be satisfied by
     * silently returning null.
     *
     * @return array{0: int, 1: string, 2: string, 3: string} professor_id, day, starts_at_time, ends_at_time
     */
    private function pickProfessor(int $subjectId, int $curriculumId, CollegeCode $college, int $termId, string $blockCode): array
    {
        $candidates = $this->professorCandidates($subjectId, $curriculumId, $college);
        if ($candidates === []) {
            throw new RuntimeException(
                "StudentRosterSeeder found no eligible professor for college '{$college->value}' (subject id {$subjectId}). ".
                'Seed at least one Faculty user for every college before running StudentRosterSeeder.',
            );
        }

        $count = count($candidates);
        $cursorKey = $subjectId.'|'.$college->value;
        $startIndex = $this->professorCursor[$cursorKey] ?? 0;
        $baseSlotIndex = $this->deterministicSlotIndex($termId, $blockCode, $subjectId);

        for ($slotOffset = 0; $slotOffset < self::SLOT_COUNT; $slotOffset++) {
            [$day, $starts, $ends] = $this->slotAt(($baseSlotIndex + $slotOffset) % self::SLOT_COUNT);
            $slotKey = $termId.':'.$day.':'.$starts;

            for ($i = 0; $i < $count; $i++) {
                $index = ($startIndex + $i) % $count;
                $professorId = $candidates[$index];
                if (! isset($this->bookedSlots[$slotKey][$professorId])) {
                    $this->bookedSlots[$slotKey][$professorId] = true;
                    $this->professorCursor[$cursorKey] = ($index + 1) % $count;

                    return [$professorId, $day, $starts, $ends];
                }
            }
        }

        $slotCount = self::SLOT_COUNT;

        throw new RuntimeException(
            "StudentRosterSeeder exhausted every eligible professor across all {$slotCount} day/time slots for ".
            "subject id {$subjectId} in college '{$college->value}' (term id {$termId}, block '{$blockCode}') without ".
            'finding a free assignment — the candidate pool or slot space is too small for this scale.',
        );
    }

    /**
     * @param  list<array{student_number: string, name: string, email: string, program_code: string, year_level: int}>  $rows
     * @return array<string, int>
     */
    private function programIdsByCode(array $rows): array
    {
        $codes = array_values(array_unique(array_column($rows, 'program_code')));

        return Program::query()->whereIn('code', $codes)->pluck('id', 'code')->all();
    }

    /**
     * Assumes exactly one `active` curriculum per program — true by
     * construction of `GrcCurriculumSeeder`, which marks only the
     * 2024-2029 version `active` and both older versions `archived`.
     *
     * @param  array<string, int>  $programIdByCode
     * @return array<int, int>
     */
    private function activeCurriculumIdsByProgramId(array $programIdByCode): array
    {
        return Curriculum::query()
            ->whereIn('program_id', array_values($programIdByCode))
            ->where('status', 'active')
            ->pluck('id', 'program_id')
            ->all();
    }

    /**
     * The full 3,210-row roster is real local/dev fixture data, not
     * something every unrelated test that happens to run the whole
     * `DatabaseSeeder` chain (e.g. `DemoEnrollmentSeederTest`) should pay
     * for or assert around. The same problem already exists for
     * `WorkbookFacultyProfileSeeder`'s `Professor_Department_List.md`, and
     * this follows its exact fix: the real default path is only used in the
     * `local` environment. An explicit constructor path (what every test of
     * this seeder itself passes) always wins, in any environment.
     */
    private function resolveRosterPath(): ?string
    {
        if ($this->rosterPath !== null) {
            return $this->rosterPath;
        }

        return app()->environment('local') && is_file(self::DEFAULT_PATH)
            ? self::DEFAULT_PATH
            : null;
    }

    /**
     * Parses only the `#### SECTION_CODE` roster tables out of the roster
     * markdown file. A line is treated as roster data only while inside a
     * section opened by a `#### ` heading, AND its first table cell matches
     * the `YYYY-NN-NNNNN` student-number shape — this is what naturally
     * excludes the `## Summary` block's aggregate tables (none of their
     * rows carry a student number in that shape) without needing to parse
     * headings at all beyond tracking "are we inside a `####` section".
     *
     * @return list<array{student_number: string, name: string, email: string, program_code: string, year_level: int}>
     */
    private function parseRoster(string $path): array
    {
        if (! is_file($path)) {
            throw new RuntimeException("StudentRosterSeeder could not find its roster file at {$path}");
        }

        $rows = [];
        $inSection = false;

        foreach (preg_split('/\R/u', File::get($path)) ?: [] as $line) {
            $trimmed = trim($line);

            if (str_starts_with($trimmed, '#### ')) {
                $inSection = true;

                continue;
            }

            if (str_starts_with($trimmed, '#')) {
                $inSection = false;

                continue;
            }

            if (! $inSection || $trimmed === '' || ! str_starts_with($trimmed, '|')) {
                continue;
            }

            $cells = array_map('trim', explode('|', trim($trimmed, '|')));
            if (count($cells) !== 7 || preg_match(self::STUDENT_NUMBER_PATTERN, $cells[0]) !== 1) {
                continue;
            }

            $rows[] = [
                'student_number' => $cells[0],
                'name' => $cells[1],
                'email' => $cells[2],
                'program_code' => $cells[3],
                'year_level' => (int) $cells[5],
            ];
        }

        return $rows;
    }

    private function guardEnvironment(): void
    {
        if (! app()->environment(['local', 'testing'])) {
            throw new RuntimeException('StudentRosterSeeder may only run locally or in testing.');
        }
    }
}
